sudo: required

services:
  - docker

language: generic

# on branches: ignore multiple commits that will queue build jobs, just run latest commit
git:
  depth: 1

# establish environment variables
env:
  - TEST_DIR=examples/azure-vnet-two-subnets

branches:
  only:
  - /^(?i:topic)-.*$/

# install terraform
before_deploy:
  - export KEY=$(cat /dev/urandom | tr -cd 'a-z' | head -c 12)
  - export PASSWORD=$KEY$(cat /dev/urandom | tr -cd 'A-Z' | head -c 2)$(cat /dev/urandom | tr -cd '0-9' | head -c 2)

# terraform deploy script
deploy:
  - provider: script
    skip_cleanup: true
    script: cd $TEST_DIR && ./deploy.sh
    on:
      repo: 10thmagnitude/terraform
      branch: topic-vnet-two-subnets

# destroy resources with Azure CLI
after_deploy:
  - docker run --rm -it \
      azuresdk/azure-cli-python \
      sh -c "az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID; \
             az group delete -y -n $KEY"
